contact_book/urls.py
from django.urls import path

from .views import (HomePageView, PersonCreateView, PersonUpdateView,
                    PersonDeleteView, PersonDetailView, EmailCreateView,
                    EmailUpdateView, EmailDeleteView, EmailSearchView, PhoneCreateView,
                    PhoneUpdateView, PhoneDeleteView, PhoneSearchView)

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('person/add/', PersonCreateView.as_view(), name='create-person'),
    path('person/update/<int:pk>/', PersonUpdateView.as_view(), name='update-person'),
    path('person/delete/<int:pk>/', PersonDeleteView.as_view(), name='delete-person'),
    path('person/<int:pk>/', PersonDetailView.as_view(), name='detail-person'),
    path('email/create/<int:person_id>/', EmailCreateView.as_view(),
         name='email-create'),
    path('email/update/<int:person_id>/<int:pk>/', EmailUpdateView.as_view(),
         name='email-update'),
    path('email/delete/<int:person_id>/<int:pk>/', EmailDeleteView.as_view(),
         name='email-delete'),
    path('email/search/', EmailSearchView.as_view(), name='email-search'),
    path('phone/create/<int:person_id>/', PhoneCreateView.as_view(),
         name='phone-create'),
    path('phone/update/<int:person_id>/<int:pk>/', PhoneUpdateView.as_view(),
         name='phone-update'),
    path('phone/delete/<int:person_id>/<int:pk>/', PhoneDeleteView.as_view(),
         name='phone-delete'),
    path('phone/search/', PhoneSearchView.as_view(), name='phone-search'),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contact_book.urls')),
    path('users/', include('users.urls')),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset_form.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

users/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views
from .views import RegisterView, CustomLogoutView

urlpatterns = [
    path('register/', RegisterView.as_view(), name='users-register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'),
         name='users-login'),
    path('logout/', CustomLogoutView.as_view(), name='users-logout'),
]

contact_book/models.py
from django.core.exceptions import ValidationError
from django.urls import reverse
from django.utils import timezone

from django.db import models
from django.contrib.auth.models import User


class Person(models.Model):
    """ Person model """

    first_name = models.CharField(max_length=20, null=False)
    second_name = models.CharField(max_length=30, null=False)
    date_added = models.DateTimeField(blank=True, null=True, default=timezone.now)
    note = models.TextField(null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.first_name} {self.second_name}'

    @staticmethod
    def get_absolute_url():
        return reverse('home')


class Email(models.Model):
    """ Email model """

    email = models.EmailField(null=False)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)

    def validate_unique(self, exclude=None):
        qs = Email.objects.filter(email=self.email).all()
        if qs.filter(person=self.person).exists():
            raise ValidationError(f"{self.email} email for this person already exists")

    def save(self, *args, **kwargs):
        self.validate_unique()
        super(Email, self).save(*args, **kwargs)

    def __str__(self):
        return f'{str(self.person)} email: {self.email}'

    def get_absolute_url(self):
        return reverse('detail-person', kwargs={'pk': self.person.pk})


class Phone(models.Model):
    """ Phone model """

    phone = models.IntegerField(null=False)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)

    def validate_unique(self, exclude=None):
        qs = Phone.objects.filter(phone=self.phone).all()
        if qs.filter(person=self.person).exists():
            raise ValidationError(f"{self.phone} number for this person already exists")

    def save(self, *args, **kwargs):
        self.validate_unique()
        super(Phone, self).save(*args, **kwargs)

    def __str__(self):
        return f'{str(self.person)} phone: {self.phone}'

    def get_absolute_url(self):
        return reverse('detail-person', kwargs={'pk': self.person.pk})

contact_book/forms.py
from django import forms
from .models import Phone, Person


class PhoneForm(forms.ModelForm):
    """ Phone number adding custom form """

    phone_num_length = 9  # Const length of phone number

    class Meta:
        model = Phone
        fields = ['phone']

    def clean_phone(self):
        """ Verifying input phone number """
        phone = self.cleaned_data['phone']

        if len(str(phone)) != PhoneForm.phone_num_length:
            raise forms.ValidationError(
                f'Number should contain {self.phone_num_length} digits: {phone}',
                code='invalid')

        return phone


class PersonSearchForm(forms.Form):
    first_name = forms.CharField(required=False, label='Search first name',
                                 widget=forms.TextInput(
                                     attrs={'placeholder': 'John'}))

    second_name = forms.CharField(required=False, label='Search second name',
                                  widget=forms.TextInput(
                                      attrs={'placeholder': 'Doe'}))

    note = forms.CharField(required=False, label='Search note',
                           widget=forms.TextInput(
                               attrs={'placeholder': 'Some note'}))


class EmailSearchForm(forms.Form):
    first_name = forms.CharField(required=False, label='Search first name',
                                 widget=forms.TextInput(
                                     attrs={'placeholder': 'John'}))

    second_name = forms.CharField(required=False, label='Search second name',
                                  widget=forms.TextInput(
                                      attrs={'placeholder': 'Doe'}))

    email = forms.CharField(required=False, label='Search email',
                            widget=forms.TextInput(
                                attrs={'placeholder': 'john.doe@example.com'}))


class PhoneSearchForm(forms.Form):
    first_name = forms.CharField(required=False, label='Search first name',
                                 widget=forms.TextInput(
                                     attrs={'placeholder': 'John'}))

    second_name = forms.CharField(required=False, label='Search second name',
                                  widget=forms.TextInput(
                                      attrs={'placeholder': 'Doe'}))

    phone = forms.CharField(required=False, label='Search phone number',
                            widget=forms.TextInput(
                                attrs={'placeholder': '111222333'}))

contact_book/views.py
from django.urls import reverse
from django.views.generic import (ListView, CreateView, UpdateView, DeleteView,
                                  DetailView, FormView)
from django.views.generic.edit import FormMixin
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from .models import Person, Email, Phone
from django.contrib.messages.views import SuccessMessageMixin
from .forms import PhoneForm, PersonSearchForm, EmailSearchForm, PhoneSearchForm


class HomePageView(LoginRequiredMixin, FormMixin, ListView):
    """ Main home page view accessible after login """

    template_name = 'contact_book/home.html'
    model = Person
    context_object_name = 'people'
    form_class = PersonSearchForm
    ordering = ['-date_added']
    paginate_by = 10

    def get_queryset(self):
        """ Get people list of a particular user """

        form = self.form_class(self.request.GET)
        user = User.objects.filter(username=self.request.user.username).first()
        if form.is_valid():
            return Person.objects.filter(
                first_name__icontains=form.cleaned_data['first_name'],
                second_name__icontains=form.cleaned_data['second_name'],
                note__icontains=form.cleaned_data['note'],
                owner=user).all()

        return Person.objects.filter(owner=user).all()


class PersonCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Person
    fields = ['first_name', 'second_name', 'note']
    success_message = 'Person created successfully!'

    def form_valid(self, form):
        """ Setting the owner of a person as a currenctly logged user """
        form.instance.owner = self.request.user
        return super().form_valid(form)


class PersonUpdateView(LoginRequiredMixin, SuccessMessageMixin, UserPassesTestMixin,
                       UpdateView):
    model = Person
    fields = ['first_name', 'second_name', 'note']
    success_message = 'Person updated successfully'

    def test_func(self):
        """ Check if user requesting to update a person is it's owner """
        person = self.get_object()
        return True if self.request.user == person.owner else False

    def form_valid(self, form):
        """ Setting the owner of a person as a currenctly logged user """
        form.instance.author = self.request.user
        return super().form_valid(form)


class PersonDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Person
    success_url = '/'

    def test_func(self):
        """ Check if user requesting to delete a person is it's owner """
        person = self.get_object()
        return True if self.request.user == person.owner else False


class PersonDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Person

    def test_func(self):
        """ Check if user requesting to see the details of a person is it's owner """
        person = self.get_object()
        return True if self.request.user == person.owner else False


class EmailCreateView(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin,
                      CreateView):
    model = Email
    fields = ['email']
    success_message = 'Email created successfully'

    @property
    def person(self):
        return Person.objects.filter(id=self.kwargs['person_id']).first()

    def post(self, request, *args, **kwargs):
        self.object = Email(person=self.person)
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def test_func(self):
        """ Check if user requesting to add email to a person is it's owner """
        return True if self.request.user == self.person.owner else False


class EmailUpdateView(LoginRequiredMixin, SuccessMessageMixin, UserPassesTestMixin,
                      UpdateView):
    model = Email
    fields = ['email']
    success_message = 'Email updated successfully'

    @property
    def person(self):
        return Person.objects.filter(id=self.kwargs['person_id']).first()

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def test_func(self):
        """ Check if user requesting to update person's email is it's owner """
        return True if self.request.user == self.person.owner else False


class EmailDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Email

    @property
    def success_url(self):
        return reverse('detail-person', kwargs={'pk': self.person.id})

    @property
    def person(self):
        return Person.objects.filter(id=self.kwargs['person_id']).first()

    def test_func(self):
        """ Check if user requesting to delete an email is owner of the person which
        holds it """
        return True if self.request.user == self.person.owner else False


class EmailSearchView(LoginRequiredMixin, FormMixin, ListView):
    """ Search email view accessible after login """

    template_name = 'contact_book/email_search.html'
    model = Email
    context_object_name = 'emails'
    form_class = EmailSearchForm

    def get_queryset(self):
        """ Get searched email list of a particular user """

        form = self.form_class(self.request.GET)
        user = User.objects.filter(username=self.request.user.username).first()
        if form.is_valid():
            return Email.objects.filter(
                person__first_name__icontains=form.cleaned_data['first_name'],
                person__second_name__icontains=form.cleaned_data['second_name'],
                email__icontains=form.cleaned_data['email'],
                person__owner=user).order_by('-person__date_added')

        return Email.objects.filter(person_owner=user).order_by('-date_added')


class PhoneCreateView(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin,
                      CreateView):
    model = Phone
    form_class = PhoneForm
    success_message = 'Phone number created successfully'

    @property
    def person(self):
        return Person.objects.filter(id=self.kwargs['person_id']).first()

    def post(self, request, *args, **kwargs):
        self.object = Phone(person=self.person)
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def test_func(self):
        """ Check if user requesting to add phone number to person is it's owner """
        return True if self.request.user == self.person.owner else False


class PhoneUpdateView(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin,
                      UpdateView):
    model = Phone
    form_class = PhoneForm
    success_message = 'Phone number updated successfully'

    @property
    def person(self):
        return Person.objects.filter(id=self.kwargs['person_id']).first()

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def test_func(self):
        """ Check if user requesting to add phone number to person is it's owner """
        return True if self.request.user == self.person.owner else False


class PhoneDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Phone

    @property
    def success_url(self):
        return reverse('detail-person', kwargs={'pk': self.person.id})

    @property
    def person(self):
        return Person.objects.filter(id=self.kwargs['person_id']).first()

    def test_func(self):
        """ Check if user requesting to delete an email is owner of the person which
        holds it """
        return True if self.request.user == self.person.owner else False


class PhoneSearchView(LoginRequiredMixin, FormMixin, ListView):
    """ Search phone view accessible after login """

    template_name = 'contact_book/phone_search.html'
    model = Phone
    context_object_name = 'phones'
    form_class = PhoneSearchForm

    def get_queryset(self):
        """ Get searched email list of a particular user """

        form = self.form_class(self.request.GET)
        user = User.objects.filter(username=self.request.user.username).first()
        if form.is_valid():
            return Phone.objects.filter(
                person__first_name__icontains=form.cleaned_data['first_name'],
                person__second_name__icontains=form.cleaned_data['second_name'],
                phone__icontains=form.cleaned_data['phone'],
                person__owner=user).order_by('-person__date_added')

        return Phone.objects.filter(person_owner=user).order_by('-date_added')

contact_book/templates/contact_book/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">

    {% if title %}
    <title>Contacts Book - {{ title }}</title>
    {% else %}
    <title>Contacts Book</title>
    {% endif %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'home' %}">Contacts book</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            {% if user.is_authenticated %}
            <a class="nav-item nav-link active" href="{% url 'create-person' %}">Add
                new person</a>
            <a class="nav-item nav-link active" href="{% url 'email-search' %}">
                Search E-mail
            </a>
            <a class="nav-item nav-link active" href="{% url 'phone-search' %}">
                Search Phone
            </a>
            <a class="nav-item nav-link" href="{% url 'users-logout' %}">Logout</a>
            {% endif %}
        </div>
    </div>
</nav>

<main role="main" class="container">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% block content %}
    {% endblock %}
</main>

</body>
</html>

contact_book/templates/contact_book/email_confirm_delete.html
{% extends "contact_book/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form action="" method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Delete email</legend>
            <h2>Are you sure you want to delete "{{ object.email }}" ?</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Delete</button>
            <a class="btn btn-outline-secondary"
               href="{% url 'home' %}">
                Cancel
            </a>
        </div>
    </form>
</div>
{% endblock content %}

contact_book/templates/contact_book/email_form.html
{% extends "contact_book/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form action="" method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">New</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Add</button>
        </div>
    </form>
</div>
{% endblock content %}

contact_book/templates/contact_book/email_search.html
{% extends "contact_book/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<h1 class="mb-3">Search emails</h1>
<hr>
<form method="get">
    {{ form|crispy }}
    <div class="form-group">
        <button class="btn btn-primary" type="submit">Search</button>
    </div>
</form>
<hr>
<article class="media content-section">
    <div class="media-body">
        <div class="mt-5 mb-5">
            <table class="table">
                <thead class="thead-dark">
                <tr>
                    <th>Person</th>
                    <th>Email</th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for email in emails %}
                <tr>
                    <td>
                        <a href="{% url 'detail-person' email.person.id %}">
                            {{ email.person.first_name }} {{ email.person.second_name }}
                        </a>
                    </td>
                    <td>{{ email.email }}</td>
                    <td>
                        <a
                                href="{% url 'email-update' person_id=email.person.id pk=email.id %}"
                                class="btn btn-info btn-sm">
                            Update
                        </a></td>
                    <td><a
                            href="{% url 'email-delete' person_id=email.person.id pk=email.id %}"
                            class="btn btn-outline-danger btn-sm">
                        Delete
                    </a></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</article>
<hr>
{% endblock content %}

contact_book/templates/contact_book/home.html
{% extends "contact_book/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<h1 class="mb-3">Hello {{user.username}}, welcome to contacts book!</h1>
<h3 class="mb-3"> Search people</h3>
<hr>
<form method="get">
    {{ form|crispy }}
    <div class="form-group">
        <button class="btn btn-primary" type="submit">Search</button>
    </div>
</form>
<hr>
<h3 class="mb-3"> Your Contacts:</h3>
{% for person in people %}
<article class="media content-section">
    <div class="media-body">
        <h2 class="mr-2 mb-0"><a href="{% url 'detail-person' person.id %}">
            {{ person.first_name }} {{ person.second_name }}
        </a></h2>
        <small class="text-muted">Added {{ person.date_added|date:"F d, Y" }}</small>
        <div>
            <a href="{% url 'update-person' person.id %}"
               class="btn btn-outline-info btn-sm mt-1 mb-1">Edit
                person</a>
            <a href="{% url 'delete-person' person.id %}"
               class="btn btn-danger btn-sm mt-1 mb-1">Delete
                person</a>
        </div>
        <h4 class="mr-2 mt-3">Notes</h4>
        <p class="mr-2">{{ person.note }}</p>
    </div>
</article>
<hr>

{% if is_paginated %}

    {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4"
           href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}

{% endif %}

{% endfor %}
{% endblock content %}

contact_book/templates/contact_book/person_confirm_delete.html
{% extends "contact_book/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form action="" method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Delete person</legend>
            <h2>Are you sure you want to delete "{{ object.first_name }}
                {{ object.second_name }} ?"</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Delete</button>
            <a class="btn btn-outline-secondary"
               href="{% url 'home' %}">
                Cancel
            </a>
        </div>
    </form>
</div>
{% endblock content %}

contact_book/templates/contact_book/person_detail.html
{% extends "contact_book/base.html" %}
{% block content %}

<article class="media content-section">
    <div class="media-body">
        <h2 class="mr-2 mb-0">{{ object.first_name }} {{ object.second_name }}</h2>
        <small class="text-muted">Added {{ object.date_added|date:"F d, Y" }}</small>
        <div>
            <a href="{% url 'update-person' object.id %}"
               class="btn btn-outline-info btn-sm mt-1 mb-1">Edit
                person</a>
            <a href="{% url 'delete-person' object.id %}"
               class="btn btn-danger btn-sm mt-1 mb-1">Delete
                person</a>
        </div>
        <div>
            <h4 class="mr-2 mt-3">Notes</h4>
            <p class="mr-2">{{ person.note }}</p>
        </div>
        <div class="mt-5 mb-5">
            <table class="table">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">Email</th>
                    <th scope="col"><a href="{% url 'email-create' object.id %}"
                                       class="btn btn-success btn-sm">
                        Add new
                    </a></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for email in object.email_set.all %}
                <tr>
                    <th scope="row">{{ email.email }}</th>
                    <td>
                        <a href="{% url 'email-update' person_id=object.id pk=email.id %}"
                           class="btn btn-info btn-sm">
                            Update
                        </a></td>
                    <td><a
                            href="{% url 'email-delete' person_id=object.id pk=email.id %}"
                            class="btn btn-outline-danger btn-sm">
                        Delete
                    </a></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="mt-5 mb-5">
            <table class="table">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">Phone number</th>
                    <th scope="col"><a href="{% url 'phone-create' object.id %}"
                                       class="btn btn-success btn-sm">
                        Add new
                    </a></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for phone in object.phone_set.all %}
                <tr>
                    <th scope="row">{{ phone.phone }}</th>
                    <td>
                        <a href="{% url 'phone-update' person_id=object.id pk=phone.id %}"
                           class="btn btn-info btn-sm">
                            Update
                        </a></td>
                    <td><a
                            href="{% url 'phone-delete' person_id=object.id pk=phone.id %}"
                            class="btn btn-outline-danger btn-sm">
                        Delete
                    </a></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <div>
            <a href="{% url 'home' %}"
               class="btn btn-outline-secondary btn-sm mt-1 mb-1">Back to
                home page</a>
        </div>

    </div>
</article>
{% endblock content %}

contact_book/templates/contact_book/person_form.html
{% extends "contact_book/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form action="" method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">New person</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Post</button>
        </div>
    </form>
</div>
{% endblock content %}

contact_book/templates/contact_book/phone_confirm_delete.html
{% extends "contact_book/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form action="" method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Delete phone</legend>
            <h2>Are you sure you want to delete "{{ object.phone }}" ?</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Delete</button>
            <a class="btn btn-outline-secondary"
               href="{% url 'detail-person' object.person.id %}">
                Cancel
            </a>
        </div>
    </form>
</div>
{% endblock content %}

contact_book/templates/contact_book/phone_form.html
{% extends "contact_book/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form action="" method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Phone number</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Add</button>
            <a class="btn btn-outline-danger"
               href="{% url 'detail-person' view.kwargs.person_id %}">Cancel</a>
        </div>
    </form>
</div>
{% endblock content %}